version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: estilo360_postgres
    restart: always
    environment:
      POSTGRES_DB: estilo360db
      POSTGRES_USER: estilo360
      POSTGRES_PASSWORD: estilo360pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: estilo360_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@estilo360.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
